// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WBot2.Data;

namespace WBot2.Migrations
{
    [DbContext(typeof(ReactionRoleContext))]
    partial class ReactionRoleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-preview.1.21102.2");

            modelBuilder.Entity("WBot2.Data.Guild", b =>
                {
                    b.Property<ulong>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("WBot2.Data.RRMessage", b =>
                {
                    b.Property<ulong>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmojiRolesJS")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("GuildID");

                    b.ToTable("WatchedMessages");
                });

            modelBuilder.Entity("WBot2.Data.RRMessage", b =>
                {
                    b.HasOne("WBot2.Data.Guild", "Guild")
                        .WithMany("ReactMessages")
                        .HasForeignKey("GuildID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("WBot2.Data.Guild", b =>
                {
                    b.Navigation("ReactMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
